services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "9090:9090"
    environment:
      - QDRANT_HOST=host.docker.internal
      - QDRANT_PORT=6333
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - rag_network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "9080:9080"
    environment:
      - BACKEND_URL=http://backend:9090
    depends_on:
      - backend
    networks:
      - rag_network

networks:
  rag_network:
    driver: bridge
